name: Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    if: github.repository_owner == 'hackingmaterials' # don't run on forks
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # pytest-split groups for automatically equally split concurrent test runners
        group: [1, 2, 3, 4, 5]
    services:
      mongodb:
        image: mongo
        ports:
          - 27017:27017

    steps:
      - name: Check out repo
        uses: actions/checkout@v2

      - name: Set up python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
          cache: pip
          cache-dependency-path: |
            setup.py
            requirements-ci.txt

      - name: Install OpenBabel
        run: |
          # underlying C++ lib needed for Python openbabel wrapper installed by `pip install .`
          sudo apt-get install libopenbabel-dev
          # https://github.com/openbabel/openbabel/issues/2408#issuecomment-1014466193
          sudo ln -s /usr/include/openbabel3 /usr/local/include/openbabel3

      - name: Install dependencies
        run: |
          pip install -r requirements-ci.txt
          pip install .[complete]

      - name: Get durations from cache
        uses: actions/cache@v2
        with:
          path: test_durations
          # the key must never match, even when restarting workflows, as that
          # will cause durations to get out of sync between groups, the
          # combined durations will be loaded if available
          key: test-durations-split-${{ github.run_id }}-${{ github.run_number}}-${{ matrix.group }}
          restore-keys: |
            test-durations-combined-${{ github.sha }}
            test-durations-combined

      - name: Run tests
        run: |
          pytest --splits 5 --group ${{ matrix.group }} --store-durations \
            --cov=atomate --cov-report html:coverage_reports atomate

      - name: Upload partial durations
        uses: actions/upload-artifact@v2
        with:
          name: split-${{ matrix.group }}
          path: .test_durations

  update_durations:
    name: Combine and update test durations
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Check out repo
        uses: actions/checkout@v2

      - name: Get durations from cache
        uses: actions/cache@v2
        with:
          path: .test_durations
          # key won't match during the first run for the given commit, but
          # restore-key will if there's a previous stored durations file,
          # so cache will both be loaded and stored
          key: test-durations-combined-${{ github.sha }}
          restore-keys: test-durations-combined

      - name: Download artifacts
        uses: actions/download-artifact@v2

      - name: Combine test durations
        run: python3 .github/workflows/combine_durations.py
