name: Testing

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Install C++ dependencies
        run: |
          snap install openbabel

      - name: Cache pip
        uses: actions/cache@v2
        id: pip-cache
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        if: steps.pip-cache.outputs.cache-hit != 'true'
        run: |
          pip install -r requirements.txt
          pip install -r requirements-ci.txt
          pip install .[complete]

      - name: pytest
        run: |
          pytest --ignore=atomate/qchem/test_files --cov=atomate --cov-report html:coverage_reports atomate
