name: Testing

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    # don't run on forks
    if: github.repository_owner == 'hackingmaterials'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Install OpenBabel
        run: |
          sudo apt-get install openbabel python3-openbabel

      - name: Cache pip
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements-ci.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          pip install -r requirements-ci.txt
          pip install .[complete]

      - name: pytest
        run: |
          pytest --ignore=atomate/qchem/test_files --cov=atomate --cov-report html:coverage_reports atomate
